name: Upload to S3

on:
  push:
    branches:
      - main  # Change this to match your branch

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: your-aws-region  # Change this to match your AWS region

      - name: Upload to S3
        run: |
          aws s3 cp README.md s3://github-action-target/action-target-folder/
